// 数据（从绘本版/像素版提取）
const GALLERY = {"lagoon": ["https://thumb.wikimedia.org/wikipedia/en/thumb/0/00/Blue_Lagoon_Main_Building.JPG/1280px-Blue_Lagoon_Main_Building.JPG", "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4b/BlueLagoon_Noface.jpg/1280px-BlueLagoon_Noface.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f4/Grindavik_area_annotated.jpg/1280px-Grindavik_area_annotated.jpg"], "thing": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/8/83/%C3%9Eingvellir_from_the_information_centre.JPG/1280px-%C3%9Eingvellir_from_the_information_centre.JPG", "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e8/Thingvellir.jpg/1280px-Thingvellir.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/48/World_Heritage_plaque_at_%C3%9Eingvellir_National_Park.jpg/1280px-World_Heritage_plaque_at_%C3%9Eingvellir_National_Park.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a3/Ca%C3%B1%C3%B3n_Silfra%2C_Parque_Nacional_de_%C3%9Eingvellir%2C_Su%C3%B0urland%2C_Islandia%2C_2014-08-16%2C_DD_055.JPG/1280px-Ca%C3%B1%C3%B3n_Silfra%2C_Parque_Nacional_de_%C3%9Eingvellir%2C_Su%C3%B0urland%2C_Islandia%2C_2014-08-16%2C_DD_055.JPG"], "geysir": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ef/Erupting_geysir.jpg/330px-Erupting_geysir.jpg"], "gullfoss": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/1/18/Gullfoss_from_the_Air_%28cropped%29.jpg/1280px-Gullfoss_from_the_Air_%28cropped%29.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6e/Iceland_-_2017-02-22_-_Gullfoss_-_3684.jpg/1280px-Iceland_-_2017-02-22_-_Gullfoss_-_3684.jpg"], "skalakot": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/4/46/043_S%C3%A6var_fr%C3%A1_Stangarholti.jpg/1280px-043_S%C3%A6var_fr%C3%A1_Stangarholti.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e6/IcelandicHorseInWinter.jpg/1280px-IcelandicHorseInWinter.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6d/271_Happad%C3%ADs_fr%C3%A1_Stangarholti.jpg/500px-271_Happad%C3%ADs_fr%C3%A1_Stangarholti.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1c/Icelandic_mare_and_foal1.jpg/1280px-Icelandic_mare_and_foal1.jpg"], "selja": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/3/33/Idyllic_landscape_with_a_waterfall_%28Unsplash%29.jpg/1280px-Idyllic_landscape_with_a_waterfall_%28Unsplash%29.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/19/Premises_of_Seljalandsfoss_25.jpg/250px-Premises_of_Seljalandsfoss_25.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a8/Icland_Seljalandsfoss_Luftbild_Sept_2019_1.jpg/250px-Icland_Seljalandsfoss_Luftbild_Sept_2019_1.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/48/Seljalandfoss_at_night.jpg/250px-Seljalandfoss_at_night.jpg"], "skoga": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8c/2008-05-24_35_Sk%C3%B3gafoss.jpg/1280px-2008-05-24_35_Sk%C3%B3gafoss.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d9/Climbing_Skogafoss_%28184087143%29.jpeg/250px-Climbing_Skogafoss_%28184087143%29.jpeg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9b/Earth%27s_Hair_-_Flickr_-_FerTravelPhoto.jpg/500px-Earth%27s_Hair_-_Flickr_-_FerTravelPhoto.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5f/Skogafoss_At_Night_%28167821181%29.jpeg/960px-Skogafoss_At_Night_%28167821181%29.jpeg"], "black": ["https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Reynisfjara_Beach_Looking_West_Towards_Dyrh%C3%B3laey.jpg/1280px-Reynisfjara_Beach_Looking_West_Towards_Dyrh%C3%B3laey.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/H%C3%A1lsanefshellir_Cave_at_Reynisfjara_Beach.jpg/1280px-H%C3%A1lsanefshellir_Cave_at_Reynisfjara_Beach.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Eyjafjallaj%C3%B6kull_Volcano_seen_from_Reynisfjara_Beach.jpg/1280px-Eyjafjallaj%C3%B6kull_Volcano_seen_from_Reynisfjara_Beach.jpg", "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Reynisfjara_Beach_Hazards_Sign.jpg/1280px-Reynisfjara_Beach_Hazards_Sign.jpg"], "jokul": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2c/J%C3%B6kuls%C3%A1rl%C3%B3n_lagoon_in_southeastern_Iceland.jpg/1280px-J%C3%B6kuls%C3%A1rl%C3%B3n_lagoon_in_southeastern_Iceland.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7a/Vatnaj%C3%B6kull_glacier.jpg/1280px-Vatnaj%C3%B6kull_glacier.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ac/Stercorarius_parasiticus-pjt.jpg/1280px-Stercorarius_parasiticus-pjt.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1c/Phoques_communs_sur_le_Jokulsarlon_en_Islande.jpg/1280px-Phoques_communs_sur_le_Jokulsarlon_en_Islande.jpg"], "rkv": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8b/Hallgrimskirkja_mai_2026.jpg/1280px-Hallgrimskirkja_mai_2026.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/60/ETH-BIB_Com_L26-0330-0020-0003_Hallgrimskirkja_xx0677.jpg/1280px-ETH-BIB_Com_L26-0330-0020-0003_Hallgrimskirkja_xx0677.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5c/View_from_the_top_of_Hallgr%C3%ADmskirkja.JPG/500px-View_from_the_top_of_Hallgr%C3%ADmskirkja.JPG", "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e1/Hallgr%C3%ADmskirkja_-_Last_Christmas_%283160371678%29.jpg/500px-Hallgr%C3%ADmskirkja_-_Last_Christmas_%283160371678%29.jpg"], "kef": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b3/SSJ100_Keflavik_runways_%285160518757%29.jpg/1280px-SSJ100_Keflavik_runways_%285160518757%29.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/40/2006-05-27-082806_Iceland_Keflav%C3%ADk.jpg/1280px-2006-05-27-082806_Iceland_Keflav%C3%ADk.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3e/Keflav%C3%ADk_International_Airport_%28seen_from_runway%29.jpg/1280px-Keflav%C3%ADk_International_Airport_%28seen_from_runway%29.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a7/Keflav%C3%ADk_Airport_interior_2018.jpg/1280px-Keflav%C3%ADk_Airport_interior_2018.jpg"], "tromso": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Troms%C3%B8_sentrum_%285835702754%29.jpg/1280px-Troms%C3%B8_sentrum_%285835702754%29.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/23/Troms%C3%B8_Docks_%28From_Above%29.jpg/1280px-Troms%C3%B8_Docks_%28From_Above%29.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a7/Hurtigruten_Polarlys.jpg/1280px-Hurtigruten_Polarlys.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a3/Ishavskatedralen_Troms%C3%B8.jpg/1280px-Ishavskatedralen_Troms%C3%B8.jpg"], "cable": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/e/eb/Fjellheisen%2C_Troms%C3%B8_2019.jpg/1280px-Fjellheisen%2C_Troms%C3%B8_2019.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/87/Fjellheisen_Upper_Station_-_Troms%C3%B8%2C_Norway_2023-07-08_%2802%29.jpg/1280px-Fjellheisen_Upper_Station_-_Troms%C3%B8%2C_Norway_2023-07-08_%2802%29.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e7/Troms%C3%B8_2013_06_05_3734_%2810118181034%29.jpg/1280px-Troms%C3%B8_2013_06_05_3734_%2810118181034%29.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a8/Panorama_fjellheisen-improved.jpg/1280px-Panorama_fjellheisen-improved.jpg"], "church": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d0/Arctic_Cathedral_in_Tromsoe.jpg/1280px-Arctic_Cathedral_in_Tromsoe.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fa/Tromsdalen_Church_South.jpg/250px-Tromsdalen_Church_South.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a6/Tromsdalen_Church_mosaic.jpg/250px-Tromsdalen_Church_mosaic.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/37/Troms%C3%B8_2015.jpg/250px-Troms%C3%B8_2015.jpg"], "whale": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/3/37/Killerwhales_jumping.jpg/1280px-Killerwhales_jumping.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/87/Orcinus_citoniensis.JPG/1280px-Orcinus_citoniensis.JPG", "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1a/Naturalis_Biodiversity_Center_-_Museum_-_Workshop_-_Lecture_hall%2C_killer_whale_skeleton_suspended_from_ceiling2.jpg/1280px-Naturalis_Biodiversity_Center_-_Museum_-_Workshop_-_Lecture_hall%2C_killer_whale_skeleton_suspended_from_ceiling2.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/38/Orca_porpoising.jpg/500px-Orca_porpoising.jpg"], "ers": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b6/Arn%C3%B8yh%C3%B8gda%2C_Laukslettinden%2C_Tjuvtinden_%26_R%C3%B8dhetta%2C_2012_March.jpg/1280px-Arn%C3%B8yh%C3%B8gda%2C_Laukslettinden%2C_Tjuvtinden_%26_R%C3%B8dhetta%2C_2012_March.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/32/Fylkesvei_292%2C_Piggtinden.JPG/1280px-Fylkesvei_292%2C_Piggtinden.JPG", "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/19/Balsfjorden_%26_Jiehkkev%C3%A1rri.jpg/1280px-Balsfjorden_%26_Jiehkkev%C3%A1rri.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/92/Musvaer_troms_norway.jpg/1280px-Musvaer_troms_norway.jpg"], "husky": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/9/98/Trond_Hansen_%288436514576%29.jpg/1280px-Trond_Hansen_%288436514576%29.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c0/Fur_Trader_in_Toboggan_oil_painting_by_Cornelius_Krieghoff.jpg/500px-Fur_Trader_in_Toboggan_oil_painting_by_Cornelius_Krieghoff.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4a/%D0%A7%D1%83%D0%BA%D0%BE%D1%82%D1%81%D0%BA%D0%B0%D1%8F_%D0%B8%D0%BB%D0%B8_%D0%BA%D0%BE%D0%BB%D1%8B%D0%BC%D1%81%D0%BA%D0%B0%D1%8F_%D0%BD%D0%B0%D1%80%D1%82%D0%B0.jpg/1280px-%D0%A7%D1%83%D0%BA%D0%BE%D1%82%D1%81%D0%BA%D0%B0%D1%8F_%D0%B8%D0%BB%D0%B8_%D0%BA%D0%BE%D0%BB%D1%8B%D0%BC%D1%81%D0%BA%D0%B0%D1%8F_%D0%BD%D0%B0%D1%80%D1%82%D0%B0.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d7/Kulusuk-sled-and-kayak.jpg/1280px-Kulusuk-sled-and-kayak.jpg"], "aurora": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d3/Aurora_borealis_over_Eielson_Air_Force_Base%2C_Alaska.jpg/1280px-Aurora_borealis_over_Eielson_Air_Force_Base%2C_Alaska.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f3/Flames_in_the_sky.jpg/1280px-Flames_in_the_sky.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9d/G5_aurora_over_Tuntorp%2C_Lysekil_Municipality_15.jpg/1280px-G5_aurora_over_Tuntorp%2C_Lysekil_Municipality_15.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/52/Aurora_australis_ISS.jpg/500px-Aurora_australis_ISS.jpg"], "sommerro": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/1/15/Winter_%286789041074%29.jpg/1280px-Winter_%286789041074%29.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9a/Nationaltheatret_evening.jpg/1280px-Nationaltheatret_evening.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c1/Boats_in_oslo.jpg/1280px-Boats_in_oslo.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/76/Oslo_%286789041914%29.jpg/1280px-Oslo_%286789041914%29.jpg"], "oslcity": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/3/39/Oslo_Opera_House_-_2025.jpg/1280px-Oslo_Opera_House_-_2025.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e5/Oslo_Opera_House_2023_2.jpg/1280px-Oslo_Opera_House_2023_2.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0b/Oslo_-_Opera_House.jpg/960px-Oslo_-_Opera_House.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/34/Oslo_-_Opera_House_-_2026.jpg/960px-Oslo_-_Opera_House_-_2026.jpg"], "kontrast": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ec/Grunerlokka_Oslo.jpg/1280px-Grunerlokka_Oslo.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e1/Olaf_Ryes_plass_vinter_skumring.jpg/1280px-Olaf_Ryes_plass_vinter_skumring.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9a/Olaf_Ryes_plass_10.jpg/1280px-Olaf_Ryes_plass_10.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/55/Olaf_Ryes_plass_9.jpg/1280px-Olaf_Ryes_plass_9.jpg"], "tos": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/4/43/Troms%C3%B8_airport%2C_Norway.jpg/1280px-Troms%C3%B8_airport%2C_Norway.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ea/SAS_DC-7C._Aircraft_on_the_ground.jpg/1280px-SAS_DC-7C._Aircraft_on_the_ground.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d0/Troms%C3%B6_airport_IMG_9060.JPG/1280px-Troms%C3%B6_airport_IMG_9060.JPG", "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b4/Troms%C3%B8_Airport_check-in.jpg/500px-Troms%C3%B8_Airport_check-in.jpg"], "osl": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f1/Oslo_Airport_terminal_night_view.jpg/1280px-Oslo_Airport_terminal_night_view.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a7/Soldiers_at_Gardermoen%2C_1904.jpg/500px-Soldiers_at_Gardermoen%2C_1904.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/81/OSLpass.JPG/500px-OSLpass.JPG", "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/90/Oslo_airport_Check_in_area.jpg/1280px-Oslo_airport_Check_in_area.jpg"], "pek": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/a/af/Aerial_view_of_Beijing_Capital_International_Airport_%28cropped%29.jpg/500px-Aerial_view_of_Beijing_Capital_International_Airport_%28cropped%29.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/Beijing_Capital_International_Airport_in_1959.jpg/500px-Beijing_Capital_International_Airport_in_1959.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5d/Arrival_of_Air_Force_One_in_Peking_-_NARA_-_194412.jpg/1280px-Arrival_of_Air_Force_One_in_Peking_-_NARA_-_194412.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/71/Air_China_Boeing_747-4J6_B-2464_%2824628702009%29.jpg/1280px-Air_China_Boeing_747-4J6_B-2464_%2824628702009%29.jpg"], "home": ["https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2d/Skyline_of_Beijing_CBD_with_B-5906_approaching_%2820211016171955%29_%281%29.jpg/1280px-Skyline_of_Beijing_CBD_with_B-5906_approaching_%2820211016171955%29_%281%29.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e0/%E6%99%AF%E5%B1%B1%E5%85%AC%E5%9B%AD_%2820315852831%29-_cropped.jpg/1280px-%E6%99%AF%E5%B1%B1%E5%85%AC%E5%9B%AD_%2820315852831%29-_cropped.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/45/Temple_of_Heaven_-_Hall_of_Prayer_for_Good_Harvests_01_%28cropped%29.jpg/1280px-Temple_of_Heaven_-_Hall_of_Prayer_for_Good_Harvests_01_%28cropped%29.jpg", "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d6/Peking_Grosse_Mauer-20071019-RM-114506.jpg/1280px-Peking_Grosse_Mauer-20071019-RM-114506.jpg"]};
const CAPS = {
  lagoon:['奶蓝色地热海水 · 蒸汽缭绕','The Retreat 私汤区','熔岩原环抱的蓝湖'],
  thing:['站在北美与欧亚板块裂缝上','Öxarárfoss 瀑布','议会旧址的雪原','冬季的辛格维利尔'],
  geysir:['Strokkur 每隔几分钟喷一次'],
  gullfoss:['双层跌水的黄金瀑布','冬日冰封的黄金瀑布'],
  skalakot:['百年庄园 · 草顶木屋','庄园里的冰岛马','斯卡拉科特山谷','农场直供的晚餐'],
  selja:['可以绕到水帘后面','冬天的塞里雅兰','水帘洞视角','瀑布下的步道'],
  skoga:['斯科加瀑布 · 晴天有彩虹','60 米宽的跌落','瀑布顶观景台','冬季的斯科加'],
  black:['玄武岩柱与黑沙滩','海蚀柱 Reynisdrangar','⚠️ 远离浪线','黑沙滩的浪'],
  jokul:['冰河湖上的浮冰','钻石沙滩','蓝冰洞内部','冰川与湖水'],
  rkv:['哈尔格林姆教堂','雷市彩色小屋','哈帕音乐厅','太阳航海者雕塑'],
  kef:['凯夫拉维克机场','KEF 跑道','冰岛航空','到达大厅'],
  tromso:['特罗姆瑟港全景','从空中看码头','海达路德邮轮夜航','北极大教堂夜景'],
  cable:['Fjellheisen 缆车','山顶看全城亮灯','特罗姆瑟全景','雪顶观景台'],
  church:['北极大教堂','三角形冰白立面','教堂夜景','内部玻璃花窗'],
  whale:['虎鲸跃出水面','座头鲸摆尾','峡湾里的鲸群','观鲸船'],
  ers:['Ersfjordbotn 明信片机位','峡湾小镇','雪山倒影','红色小木屋'],
  husky:['狗拉雪橇出发！','精力旺盛的哈士奇','雪原上的雪橇队','营地的小狗们'],
  aurora:['极光舞动','绿光铺满夜空','篝火旁等极光','极光下的雪原'],
  sommerro:['阿克尔码头冬景','国家剧院夜景（酒店附近）','奥斯陆港湾','冬日码头'],
  oslcity:['奥斯陆歌剧院 · 屋顶随便走','卡尔约翰大街','阿克尔码头','歌剧院夜景'],
  kontrast:['Grünerløkka 街区 · Kontrast 在这','Olaf Ryes 广场冬夜','Vulkan 区街景','街区漫步'],
  tos:['特罗姆瑟机场','TOS 跑道','雪山边的机场','候机厅'],
  osl:['奥斯陆机场','OSL 航站楼','值机中','登机口'],
  pek:['北京首都机场','出发！','国航商务舱','首都机场夜景'],
  home:['北京 · 到家啦','熟悉的 skyline','欢迎回家 🎉','旅程圆满结束'],
};
const DAYS = [
 {date:'1月11日', wd:'周一', title:'抵达 + 蓝湖', region:'ice', steps:[
   {t0:0,   t1:3.5,  mode:'plane', from:'pek',   to:'pek',   label:'北京 03:30 起飞（经停哥本哈根）', region:'ice'},
   {t0:3.5, t1:11.25,mode:'plane', from:'pek',   to:'kef',   label:'国航 北京 → 雷克雅未克，11:15 落地', region:'ice'},
   {t0:11.25,t1:11.75,mode:'car',  from:'kef',   to:'lagoon',label:'落地啦！包车 20 分钟直奔蓝湖'},
   {t0:11.75,t1:17,  mode:'stay',  from:'lagoon',to:'lagoon',label:'入住 The Retreat · 私汤倒时差'},
   {t0:17,  t1:18,   mode:'walk',  from:'lagoon',to:'lagoon',label:'蓝湖暮色散步 · 硅泥面膜'},
   {t0:18,  t1:21,   mode:'stay',  from:'lagoon',to:'lagoon',label:'🍽 Moss 米其林一星（18:00 订位）'},
   {t0:21,  t1:24,   mode:'sleep', from:'lagoon',to:'lagoon',label:'🏨 夜宿 The Retreat at Blue Lagoon'},
 ]},
 {date:'1月12日', wd:'周二', title:'蓝湖休整日（倒时差）', region:'ice', steps:[
   {t0:0,   t1:9,    mode:'sleep', from:'lagoon',to:'lagoon',label:'🏨 夜宿 The Retreat'},
   {t0:9,   t1:11.5, mode:'stay',  from:'lagoon',to:'lagoon',label:'晨泡私汤 · 几乎没有人'},
   {t0:11.5,t1:14,   mode:'walk',  from:'lagoon',to:'lagoon',label:'熔岩原散步 + 蓝湖面膜'},
   {t0:14,  t1:17,   mode:'stay',  from:'lagoon',to:'lagoon',label:'Retreat Spa · 干蒸 / 冷水池'},
   {t0:17,  t1:18.5, mode:'walk',  from:'lagoon',to:'lagoon',label:'酒店 lounge 看雪发呆'},
   {t0:18.5,t1:21,   mode:'stay',  from:'lagoon',to:'lagoon',label:'🍽 Lava 餐厅（蓝湖景观位）'},
   {t0:21,  t1:24,   mode:'sleep', from:'lagoon',to:'lagoon',label:'🏨 夜宿 The Retreat'},
 ]},
 {date:'1月13日', wd:'周三', title:'黄金圈 → 住庄园', region:'ice', steps:[
   {t0:0,   t1:9,    mode:'sleep', from:'lagoon',to:'lagoon',label:'🏨 夜宿 The Retreat'},
   {t0:9,   t1:9.75, mode:'car',   from:'lagoon',to:'thing', label:'出发！黄金圈一日游（约 45min）'},
   {t0:9.75,t1:11.75,mode:'walk',  from:'thing', to:'thing', label:'辛格维利尔 · 站在两大板块裂缝上'},
   {t0:11.75,t1:12.75,mode:'car',  from:'thing', to:'geysir',label:'前往间歇泉'},
   {t0:12.75,t1:14,  mode:'walk',  from:'geysir',to:'geysir',label:'盖歇尔间歇泉 · 几分钟喷一次'},
   {t0:14,  t1:14.5, mode:'car',   from:'geysir',to:'gullfoss',label:'前往黄金瀑布'},
   {t0:14.5,t1:15.75,mode:'walk',  from:'gullfoss',to:'gullfoss',label:'黄金瀑布 · 双层跌水超震撼'},
   {t0:15.75,t1:16.5,mode:'car',   from:'gullfoss',to:'skalakot',label:'南下，今晚住百年庄园'},
   {t0:16.5,t1:18,   mode:'walk',  from:'skalakot',to:'skalakot',label:'庄园逛逛 · 撸冰岛马'},
   {t0:18,  t1:20.5, mode:'stay',  from:'skalakot',to:'skalakot',label:'🍽 Skálakot 庄园晚餐（农场直供）'},
   {t0:20.5,t1:24,   mode:'sleep', from:'skalakot',to:'skalakot',label:'🏨 夜宿 Skálakot Manor'},
 ]},
 {date:'1月14日', wd:'周四', title:'南岸瀑布 → 黑沙滩 → 冰河湖', region:'ice', steps:[
   {t0:0,   t1:8.5,  mode:'sleep', from:'skalakot',to:'skalakot',label:'🏨 夜宿 Skálakot Manor'},
   {t0:8.5, t1:9,    mode:'car',   from:'skalakot',to:'selja', label:'出发！南岸瀑布三连'},
   {t0:9,   t1:10,   mode:'walk',  from:'selja',  to:'selja',  label:'塞里雅兰瀑布 · 绕到水帘后面'},
   {t0:10,  t1:10.5, mode:'car',   from:'selja',  to:'skoga',  label:'前往斯科加瀑布'},
   {t0:10.5,t1:11.5, mode:'walk',  from:'skoga',  to:'skoga',  label:'斯科加瀑布 · 晴天有彩虹'},
   {t0:11.5,t1:12.25,mode:'car',   from:'skoga',  to:'black',  label:'前往维克小镇'},
   {t0:12.25,t1:14.5,mode:'walk',  from:'black',  to:'black',  label:'维克午餐 + Reynisfjara 黑沙滩（⚠️远离浪线）'},
   {t0:14.5,t1:17.5, mode:'car',   from:'black',  to:'jokul',  label:'1 号公路一路向东 · 约 3 小时'},
   {t0:17.5,t1:18.5, mode:'stay',  from:'jokul',  to:'jokul',  label:'入住 Hótel Jökulsárlón · 离冰河湖 8 分钟'},
   {t0:18.5,t1:20.5, mode:'stay',  from:'jokul',  to:'jokul',  label:'🍽 酒店晚餐 · 户外泡池等极光'},
   {t0:20.5,t1:24,   mode:'sleep', from:'jokul',  to:'jokul',  label:'🏨 夜宿 Hótel Jökulsárlón'},
 ]},
 {date:'1月15日', wd:'周五', title:'蓝冰洞（全程重头戏）', region:'ice', steps:[
   {t0:0,   t1:8.75, mode:'sleep', from:'jokul',  to:'jokul',  label:'🏨 夜宿 Hótel Jökulsárlón'},
   {t0:8.75,t1:9.5,  mode:'walk',  from:'jokul',  to:'jokul',  label:'8 分钟到冰洞集合点'},
   {t0:9.5, t1:13.5, mode:'walk',  from:'jokul',  to:'jokul',  label:'🧊 蓝冰洞探险！9:30 团（天气差保底改 1/16）'},
   {t0:13.5,t1:14.5, mode:'stay',  from:'jokul',  to:'jokul',  label:'回酒店暖一暖 + 午餐'},
   {t0:14.5,t1:16.5, mode:'walk',  from:'jokul',  to:'jokul',  label:'冰河湖 + 钻石沙滩 · 日落前最美'},
   {t0:16.5,t1:18.5, mode:'stay',  from:'jokul',  to:'jokul',  label:'酒店桑拿 · 休整'},
   {t0:18.5,t1:20.5, mode:'stay',  from:'jokul',  to:'jokul',  label:'🍽 酒店晚餐'},
   {t0:20.5,t1:24,   mode:'sleep', from:'jokul',  to:'jokul',  label:'🏨 夜宿 Hótel Jökulsárlón'},
 ]},
 {date:'1月16日', wd:'周六', title:'回雷市（车上补觉日）', region:'ice', steps:[
   {t0:0,   t1:9,    mode:'sleep', from:'jokul',  to:'jokul',  label:'🏨 夜宿 Hótel Jökulsárlón'},
   {t0:9,   t1:12,   mode:'car',   from:'jokul',  to:'black',  label:'返程南岸（全天 4.5-5h 车上补觉）'},
   {t0:12,  t1:13,   mode:'walk',  from:'black',  to:'black',  label:'维克午餐 + 教堂山看海'},
   {t0:13,  t1:16,   mode:'car',   from:'black',  to:'rkv',    label:'继续开，回雷克雅未克'},
   {t0:16,  t1:19,   mode:'stay',  from:'rkv',    to:'rkv',    label:'入住 Consulate Hotel · 连住 2 晚'},
   {t0:19,  t1:21.5, mode:'walk',  from:'rkv',    to:'rkv',    label:'🍽 Tides 19:30（Dill 主厨姊妹店，步行 6 分钟）'},
   {t0:21.5,t1:24,   mode:'sleep', from:'rkv',    to:'rkv',    label:'🏨 夜宿 Consulate Hotel'},
 ]},
 {date:'1月17日', wd:'周日', title:'雷市全天 + Sky Lagoon', region:'ice', steps:[
   {t0:0,   t1:10,   mode:'sleep', from:'rkv',    to:'rkv',    label:'🏨 夜宿 Consulate'},
   {t0:10,  t1:12,   mode:'walk',  from:'rkv',    to:'rkv',    label:'哈尔格林姆教堂登顶看彩色屋顶'},
   {t0:12,  t1:14,   mode:'walk',  from:'rkv',    to:'rkv',    label:'主街 Laugavegur 逛店 + 午餐'},
   {t0:14,  t1:16.5, mode:'walk',  from:'rkv',    to:'rkv',    label:'哈帕音乐厅 + 太阳航海者雕塑'},
   {t0:16.5,t1:19,   mode:'stay',  from:'rkv',    to:'rkv',    label:'Sky Lagoon 七步疗法（打车 10min）'},
   {t0:19.5,t1:21.5, mode:'walk',  from:'rkv',    to:'rkv',    label:'🍽 Grillmarkaðurinn 烧烤市场 19:30'},
   {t0:21.5,t1:24,   mode:'sleep', from:'rkv',    to:'rkv',    label:'🏨 夜宿 Consulate'},
 ]},
 {date:'1月18日', wd:'周一', title:'飞特罗姆瑟 + 缆车夜景', region:'trom', steps:[
   {t0:0,   t1:4.5,  mode:'sleep', from:'rkv',    to:'rkv',    label:'🏨 夜宿 Consulate', region:'ice'},
   {t0:4.5, t1:5.5,  mode:'car',   from:'rkv',    to:'kef',    label:'04:30 摸黑送机 · 冰岛包车结束', region:'ice'},
   {t0:5.5, t1:7.8,  mode:'stay',  from:'kef',    to:'kef',    label:'KEF 值机 · 07:50 起飞', region:'ice'},
   {t0:7.8, t1:12.75,mode:'plane', from:'kef',    to:'tos',    label:'冰岛航空直飞 2h55m（仅周一/周五有）', region:'trom'},
   {t0:12.75,t1:13.25,mode:'car',  from:'tos',    to:'tromso', label:'机场 → 市区 15 分钟'},
   {t0:13.25,t1:17,  mode:'stay',  from:'tromso', to:'tromso', label:'入住民宿 · 连住 4 晚 · 港口散步'},
   {t0:17,  t1:18.5, mode:'walk',  from:'tromso', to:'cable',  label:'Fjellheisen 缆车 · 山顶看全城亮灯'},
   {t0:19.5,t1:21.5, mode:'stay',  from:'tromso', to:'tromso', label:'🍽 Arctandria 海鲜（鳕鱼舌 / 帝王蟹）'},
   {t0:21.5,t1:24,   mode:'walk',  from:'tromso', to:'tromso', label:'🌌 码头蹲极光 · 第一晚'},
 ]},
 {date:'1月19日', wd:'周二', title:'市区 + 极光追猎团', region:'trom', steps:[
   {t0:0,   t1:10,   mode:'sleep', from:'tromso', to:'tromso', label:'🏠 夜宿民宿'},
   {t0:10,  t1:12.5, mode:'walk',  from:'tromso', to:'church', label:'北极大教堂 + 极地博物馆'},
   {t0:12.5,t1:14.5, mode:'walk',  from:'church', to:'tromso', label:'🍽 Mathallen 美食广场午餐'},
   {t0:14.5,t1:17,   mode:'walk',  from:'tromso', to:'tromso', label:'Kaffebønna 咖啡 · 备齐暖宝宝'},
   {t0:18,  t1:18.75,mode:'car',   from:'tromso', to:'aurora', label:'极光团小巴 18:00 出发'},
   {t0:18.75,t1:24,  mode:'stay',  from:'aurora', to:'aurora', label:'🌌 追极光！篝火晚餐 + 摄影跟拍（约 6h）'},
 ]},
 {date:'1月20日', wd:'周三', title:'懒觉 + 狗拉雪橇', region:'trom', steps:[
   {t0:0,   t1:10.5, mode:'sleep', from:'tromso', to:'tromso', label:'🏠 睡到自然醒（昨晚极光团凌晨才回）'},
   {t0:11,  t1:11.75,mode:'car',   from:'tromso', to:'husky',  label:'营地接送（约 40min）· 订下午场'},
   {t0:11.75,t1:15,  mode:'walk',  from:'husky',  to:'husky',  label:'🛷 狗拉雪橇！极夜蓝光里跑雪原（也可换驯鹿+萨米营）'},
   {t0:15,  t1:15.75,mode:'car',   from:'husky',  to:'tromso', label:'回市区'},
   {t0:18,  t1:20,   mode:'stay',  from:'tromso', to:'tromso', label:'🍽 Skirri / Full Steam 海鲜（码头边）'},
   {t0:21,  t1:23,   mode:'walk',  from:'tromso', to:'tromso', label:'🌌 码头蹲极光 · 第二晚 · 早睡养精神'},
   {t0:23,  t1:24,   mode:'sleep', from:'tromso', to:'tromso', label:'🏠 夜宿民宿'},
 ]},
 {date:'1月21日', wd:'周四', title:'峡湾观鲸', region:'trom', steps:[
   {t0:0,   t1:8,    mode:'sleep', from:'tromso', to:'tromso', label:'🏠 夜宿民宿 · 昨晚早睡体力满格'},
   {t0:8,   t1:8.5,  mode:'walk',  from:'tromso', to:'tromso', label:'码头集合（约 8:30）'},
   {t0:8.5, t1:9,    mode:'boat',  from:'tromso', to:'whale',  label:'大船出峡湾'},
   {t0:9,   t1:14.5, mode:'stay',  from:'whale',  to:'whale',  label:'🐋 峡湾观鲸 5-6h · 虎鲸 / 座头鲸'},
   {t0:14.5,t1:15,   mode:'boat',  from:'whale',  to:'tromso', label:'返航'},
   {t0:15,  t1:17,   mode:'walk',  from:'tromso', to:'tromso', label:'回民宿补觉 / Ersfjordbotn 明信片机位'},
   {t0:18.5,t1:20.5, mode:'stay',  from:'tromso', to:'tromso', label:"🍽 Bardus / Emma's · 特罗姆瑟最后一晚"},
   {t0:20.5,t1:24,   mode:'sleep', from:'tromso', to:'tromso', label:'🏠 夜宿民宿'},
 ]},
 {date:'1月22日', wd:'周五', title:'飞奥斯陆 + 歌剧院 + 逛街', region:'osl', steps:[
   {t0:0,   t1:7.75, mode:'sleep', from:'tromso', to:'tromso', label:'🏠 夜宿民宿', region:'trom'},
   {t0:7.75,t1:8,    mode:'car',   from:'tromso', to:'tos',    label:'酒店 → TOS 15 分钟', region:'trom'},
   {t0:8,   t1:9.5,  mode:'stay',  from:'tos',    to:'tos',    label:'值机 · 09:30 起飞', region:'trom'},
   {t0:9.5, t1:11.5, mode:'plane', from:'tos',    to:'osl',    label:'TOS → OSL 约 2 小时', region:'osl'},
   {t0:11.5,t1:12.25,mode:'car',   from:'osl',    to:'sommerro',label:'机场快线 20min 进城 · 寄存行李'},
   {t0:12.25,t1:14,  mode:'stay',  from:'sommerro',to:'sommerro',label:'Ekspedisjonshallen 午餐（最出片大厅）'},
   {t0:14,  t1:17,   mode:'walk',  from:'sommerro',to:'oslcity',label:'歌剧院屋顶随便走 + 卡尔约翰大街 → 阿克尔码头'},
   {t0:17,  t1:19,   mode:'walk',  from:'oslcity',to:'sommerro',label:'回酒店换装休息'},
   {t0:19,  t1:19.5, mode:'walk',  from:'sommerro',to:'kontrast',label:'前往 Vulkan 区'},
   {t0:19.5,t1:22.5, mode:'stay',  from:'kontrast',to:'kontrast',label:'🍽 Kontrast 19:30 · 米二告别大餐（🔴 提前 3-6 周订）'},
   {t0:22.5,t1:24,   mode:'sleep', from:'sommerro',to:'sommerro',label:'🏨 夜宿 Sommerro'},
 ]},
 {date:'1月23日', wd:'周六', title:'回国', region:'osl', steps:[
   {t0:0,   t1:9,    mode:'sleep', from:'sommerro',to:'sommerro',label:'🏨 夜宿 Sommerro'},
   {t0:9,   t1:9.75, mode:'stay',  from:'sommerro',to:'sommerro',label:'退房 · 和朋友一起去机场'},
   {t0:9.75,t1:10.5, mode:'car',   from:'sommerro',to:'osl',    label:'机场快线 / 打车 45min'},
   {t0:10.5,t1:12.5, mode:'stay',  from:'osl',    to:'osl',    label:'值机 · 一起 12:30 海航飞北京'},
   {t0:12.5,t1:24,   mode:'plane', from:'osl',    to:'home',   label:'✈️ 一起回家！🎉'},
 ]},
];
const LOC = {
  pek:{x:0,sc:'city',n:'北京',b:'北京 · 出发'},
  kef:{x:800,sc:'airport',n:'凯夫拉维克机场',b:'KEF 凯夫拉维克机场'},
  lagoon:{x:1600,sc:'lagoon',n:'蓝湖',b:'蓝湖 THE RETREAT'},
  thing:{x:2400,sc:'rift',n:'辛格维利尔',b:'辛格维利尔国家公园'},
  geysir:{x:3200,sc:'geysir',n:'间歇泉',b:'盖歇尔间歇泉'},
  gullfoss:{x:4000,sc:'waterfall2',n:'黄金瀑布',b:'黄金瀑布 GULLFOSS'},
  skalakot:{x:4800,sc:'manor',n:'Skálakot 庄园',b:'SKÁLAKOT 庄园'},
  selja:{x:5600,sc:'waterfall',n:'塞里雅兰瀑布',b:'塞里雅兰瀑布'},
  skoga:{x:6400,sc:'waterfall',n:'斯科加瀑布',b:'斯科加瀑布'},
  black:{x:7200,sc:'blacksand',n:'黑沙滩',b:'REYNISFJARA 黑沙滩'},
  jokul:{x:8000,sc:'glacier',n:'冰河湖',b:'冰河湖 JÖKULSÁRLÓN'},
  rkv:{x:8800,sc:'town',n:'雷克雅未克',b:'雷克雅未克市区'},
  tos:{x:9600,sc:'airport',n:'特罗姆瑟机场',b:'TOS 特罗姆瑟机场'},
  tromso:{x:10400,sc:'harbor',n:'特罗姆瑟',b:'特罗姆瑟 TROMSØ'},
  cable:{x:11200,sc:'cable',n:'缆车',b:'FJELLHEISEN 缆车'},
  church:{x:12000,sc:'cathedral',n:'北极大教堂',b:'北极大教堂'},
  whale:{x:12800,sc:'sea',n:'观鲸峡湾',b:'观鲸峡湾'},
  ers:{x:13600,sc:'fjordtown',n:'Ersfjordbotn',b:'ERSFJORDBOTN 峡湾小镇'},
  husky:{x:14400,sc:'camp',n:'雪橇营地',b:'狗拉雪橇营地'},
  aurora:{x:15200,sc:'snowfield',n:'极光观测点',b:'极光观测点'},
  sommerro:{x:16000,sc:'hotel',n:'Sommerro',b:'SOMMERRO 酒店'},
  oslcity:{x:16800,sc:'opera',n:'歌剧院',b:'奥斯陆歌剧院'},
  kontrast:{x:17600,sc:'restaurant',n:'Kontrast',b:'KONTRAST 米二'},
  osl:{x:18400,sc:'airport',n:'奥斯陆机场',b:'OSL 奥斯陆机场'},
  home:{x:19200,sc:'city',n:'北京',b:'回家啦 🎉'}
};
